# from .views_lab9 import companies,companiesById,vacancies,vacanciesByCompanies,vacanciesById,vacanciesTopTen
# from .fbv import companies,companiesById,vacancies,vacanciesByCompanies,vacanciesById,
# from .cbv import CompanyListAPIView,CompanyDetailsAPIView,VacancyListAPIView,VacancyDetailsAPIView,VacanciesByCompaniesAPIView,VacanciesTopTenAPIView
# from .generic_1 import CompanyList,CompanyDetails,VacancyList,VacancyDetails,VacanciesByCompanies,VacanciesTopTen
from .generic_2 import CompanyList,CompanyDetails,VacancyList,VacancyDetails,VacanciesByCompanies,VacanciesTopTen